return {}
--return {
--  "nvim-neo-tree/neo-tree.nvim",
--  branch = "v3.x",
--  dependencies = {
--    "nvim-lua/plenary.nvim",
--    "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
--    "MunifTanjim/nui.nvim",
--    "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
--  },
--  -- keys = {
--  --   {
--  --     "<leader>pv",
--  --     "<cmd>Neotree<cr>",
--  --     desc = "Toggle Neotree",
--  --   },
--  -- },
--  opts = {
--    sources = { "filesystem", "buffers", "git_status" },
--    -- open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
--    filesystem = {
--      filtered_items = {
--        hide_gitignored = true,
--      },
--      follow_current_file = {
--        enabled = true,
--        leave_dirs_open = true,
--      },
--    },
--    --hijack_netrw_behavior = "open_default",
--    window = {
--      mappings = {
--        ["l"] = "open",
--        ["h"] = "close_node",
--        ["<space>"] = "none",
--        ["Y"] = {
--          function(state)
--            local node = state.tree:get_node()
--            local path = node:get_id()
--            vim.fn.setreg("+", path, "c")
--          end,
--          desc = "Copy Path to Clipboard",
--        },
--        ["O"] = {
--          function(state)
--            require("lazy.util").open(state.tree:get_node().path, { system = true })
--          end,
--          desc = "Open with System Application",
--        },
--        ["P"] = { "toggle_preview", config = { use_float = false } },
--      },
--    },
--    default_component_configs = {
--      indent = {
--        with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
--        expander_collapsed = "",
--        expander_expanded = "",
--        expander_highlight = "NeoTreeExpander",
--      },
--      git_status = {
--        symbols = {
--          unstaged = "󰄱",
--          staged = "󰱒",
--        },
--      },
--    },
--  },
--}
